--- 
abstract: Force UTF-8 flag for DBIx::Simple data
author: ITO Nobuaki <daydream.trippers+cpan@gmail.com>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Simple-UTF8Columns
no_index: 
  directory: 
    - inc
    - t
requires: 
  DBIx::Simple: 1.28
  perl: 5.8.1
version: 0.02
